name: Deploy to Runcloud

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/antoine/webapps/jirafy
            git pull origin main

            # Backend Laravel
            cd api
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan queue:restart || true

            # Frontend React
            cd ../client
            npm ci
            npm run build

            # Redémarrer les services si nécessaire
            sudo supervisorctl restart all || true
