name: Laravel CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: jirafy_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo, pdo_mysql, dom, fileinfo
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: api/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('api/composer.lock') }}

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
        working-directory: api

      - name: Copy .env
        run: cp .env.example .env
        working-directory: api

      - name: Generate application key
        run: php artisan key:generate
        working-directory: api

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h"127.0.0.1" -uroot -proot --silent; do
            sleep 1
          done

      - name: Run migrations
        run: php artisan migrate --force
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: jirafy_test
          DB_USERNAME: root
          DB_PASSWORD: root
        working-directory: api

      - name: Run tests
        run: php artisan test --testsuite=Unit,Feature
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: jirafy_test
          DB_USERNAME: root
          DB_PASSWORD: root
        working-directory: api
