name: Laravel CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: jirafy_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo, pdo_pgsql, dom, fileinfo, xml, zip, bcmath
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: api/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('api/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-dev
        working-directory: api

      - name: Copy .env
        run: cp .env.testing .env
        working-directory: api

      - name: Generate application key
        run: php artisan key:generate
        working-directory: api

      - name: Run migrations
        run: php artisan migrate --force
        env:
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: jirafy_test
          DB_USERNAME: postgres
          DB_PASSWORD: password
        working-directory: api

      - name: Seed database
        run: php artisan db:seed --force
        env:
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: jirafy_test
          DB_USERNAME: postgres
          DB_PASSWORD: password
        working-directory: api

      - name: Run PHPUnit tests
        run: php artisan test
        env:
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: jirafy_test
          DB_USERNAME: postgres
          DB_PASSWORD: password
        working-directory: api

      - name: Run Codeception Acceptance tests (optional)
        run: vendor/bin/codecept run acceptance
        env:
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: jirafy_test
          DB_USERNAME: postgres
          DB_PASSWORD: password
        working-directory: api
        continue-on-error: true
