name: React CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  react-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: client

      - name: Run ESLint
        run: npm run lint
        working-directory: client

      - name: Type check
        run: npx tsc --noEmit
        working-directory: client

      - name: Build application
        run: npm run build
        working-directory: client

      - name: Preview build (optional test)
        run: |
          npm run preview &
          sleep 5
          curl -f http://localhost:4173 || exit 1
        working-directory: client
        timeout-minutes: 2

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vite-build
          path: client/dist/
          retention-days: 7
